### ISSUE TITLE
Unclear how to structure MQTT sensor message to populate portal

### ISSUE THREAD

**Issue by rreinold** [aalcott14/smart-monitoring#2]
Followed the SensorPayload JSDoc documentation to generate this MQTT Message:

```json
{
	"edge_id": "first_edge",
	"sensor_message": {
		"batteryLevel": 100,
		"dataValue": 10,
		"sensorID": 111111,
		"signalStrength": 10,
		"messageDate": "2019-01-01T00:00:00Z"
	}
}
```

But in Portal, first_edge still shows 'Waiting on incoming data' and the widget below it shows 'The datasource has returned an unexpected type of string, while this widget was expecting array'

**Comment by aalcott14** [comment]
All values in the payload should be strings.

The 'smart_monitoring' portal is configured to subscribe to messages sent from edge to platform, using topic 'sensor/[sensorname]/_platform and in order for the chart to display the incoming messages (where it says 'The datasource has returned an unexpected......') there must be messages that fall within the range indicated by the two date inputs to the left.

Same applies to the 'smart_monitoring_edge' portal except it is configured to receive messages from the platform using topic 'sensor/[sensorname]/_broadcast'.

**Comment by rreinold** [comment]
That worked. Thank you.
